pool:
  vmimage: windows-latest

trigger:
  - main

variables:
  BuildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: "Use .NET Core sdk 1.1.x"
    inputs:
      version: 1.1.x

  - task: UseDotNet@2
    displayName: "Use .NET Core sdk 2.x"
    inputs:
      version: 2.x

  - task: UseDotNet@2
    displayName: "Use .NET Core sdk 3.0.x"
    inputs:
      version: 3.0.x

  - task: UseDotNet@2
    displayName: "Use .NET Core sdk 3.1.x"
    inputs:
      version: 3.1.x

  - task: UseDotNet@2
    displayName: "Use .NET Core sdk 5.0.x"
    inputs:
      version: 5.0.x

  - task: UseDotNet@2
    displayName: "Use .NET Core sdk 6.0.x"
    inputs:
      version: 6.0.x

  - task: UseDotNet@2
    displayName: "Use .NET Core sdk 7.0.x"
    inputs:
      version: 7.0.x

  - task: DownloadSecureFile@1
    name: snkFile # The name with which to reference the secure file's path on the agent, like $(snkFile.secureFilePath)
    inputs:
      secureFile: Microsoft.Extensions.Logging.Log4Net.AspNetCoreKey.snk

  - bash: |
      cp $SNKFILE_SECUREFILEPATH $BUILD_SOURCESDIRECTORY/src/Microsoft.Extensions.Logging.Log4Net.AspNetCore
    displayName: "Bash Script"

  - task: DotNetCoreCLI@2
    displayName: "dotnet restore"
    inputs:
      command: restore
      projects: "$(Build.SourcesDirectory)/**/*csproj"

  - task: DotNetCoreCLI@2
    displayName: "dotnet build"
    inputs:
      projects: |
        $(Build.SourcesDirectory)/**/*csproj
        !$(Build.SourcesDirectory)/**/NetFrameworkv4_7_2/*.csproj
      arguments: "--configuration $(BuildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: "dotnet test"
    inputs:
      command: test
      projects: |
        $(Build.SourcesDirectory)/**/*.csproj
        !$(Build.SourcesDirectory)/**/NetFramework.v472.Tests/*.csproj
      arguments: "--configuration $(BuildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: pack
      includesymbols: true
      packagesToPack: "$(Build.SourcesDirectory)/**/Microsoft.Extensions.Logging.Log4Net.AspNetCore.csproj"
      versioningScheme: "off"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: nuget"
    inputs:
      ArtifactName: nuget
