pool:
  vmimage: windows-latest

trigger:
  - main

variables:
  BuildConfiguration: "Release"
  SupportedVersions:
    ["1.1.x", "2.x", "3.0.x", "3.1.x", "5.0.x", "6.0.x", "7.0.x", "8.0.x"]

steps:
  - ${{ each version in variables.SupportedVersions }}:
    - task: UseDotNet@2
      displayName: "Use .NET Core sdk " ${{ version }}
      inputs:
        version: $(version)

  - task: DownloadSecureFile@1
    name: snkFile # The name with which to reference the secure file's path on the agent, like $(snkFile.secureFilePath)
    inputs:
      secureFile: Microsoft.Extensions.Logging.Log4Net.AspNetCoreKey.snk

  - bash: |
      cp $SNKFILE_SECUREFILEPATH $BUILD_SOURCESDIRECTORY/src/Microsoft.Extensions.Logging.Log4Net.AspNetCore
    displayName: "Bash Script"

  - task: DotNetCoreCLI@2
    displayName: "dotnet restore"
    inputs:
      command: restore
      projects: "$(Build.SourcesDirectory)/**/*csproj"

  - task: DotNetCoreCLI@2
    displayName: "dotnet build"
    inputs:
      projects: $(Build.SourcesDirectory)/**/*csproj
      arguments: "--configuration $(BuildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: "dotnet test"
    inputs:
      command: test
      projects: $(Build.SourcesDirectory)/**/*.csproj
      arguments: "--configuration $(BuildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: pack
      includesymbols: true
      packagesToPack: "$(Build.SourcesDirectory)/**/Microsoft.Extensions.Logging.Log4Net.AspNetCore.csproj"
      versioningScheme: "off"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: nuget"
    inputs:
      ArtifactName: nuget
