name: 👀 Pull Request Checks
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, synchronize]

env:
  SOLUTION_PATH: ./src/Microsoft.Extensions.Logging.Log4net.sln

jobs:
  build:
    name: 🚀🧪 Test PR
    runs-on: windows-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: 🏗 Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            8.0.x
            7.0.x
            6.0.x
            5.0.x
            3.1.x

      - name: 🛠 Restore packages
        run: dotnet restore "${{ env.SOLUTION_PATH }}"

      - name: 🧪 Test
        run: dotnet test "${{ env.SOLUTION_PATH }}"
